{% set name = "open-notebook" %}
{% set version = "0.2.0" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/open_notebook-{{ version }}.tar.gz
  sha256: 6083ab9b8df6b4ff2d4e0528b752e40186b93e443efc1a6fbe458c79199c6d8f

build:
  entry_points:
    - nopen = open_notebook.cli:main
    - open-notebook = open_notebook.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch-fancy-pypi-readme
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - tomli
    - typing_extensions

test:
  imports:
    - open_notebook
  commands:
    - pip check
    - open-notebook --help
    - nopen --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/usnistgov/open-notebook
  summary: Command line program to open jupyter notebooks from single server
  description: |
    Command line program to open jupyter notebooks from single server
  license: NIST-PD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wpk-nist-gov
